# Обход блокировки hashicorp
ENV['VAGRANT_SERVER_URL'] = 'https://vagrant.elab.pro'

Vagrant.configure("2") do |config|

    config.vm.provider :virtualbox do |v|
        v.memory = 512
    end

    config.vm.define "dbserver" do |db|
        db.vm.box = "ubuntu/xenial64"
        db.vm.hostname = "dbserver"
        # db.vm.network :private_network, ip: "10.10.10.10"
        db.vm.network :private_network, ip: "192.168.56.10"
    end

    config.vm.define "appserver" do |app|
        app.vm.box = "ubuntu/xenial64"
        app.vm.hostname = "appserver"
        # app.vm.network :private_network, ip: "10.10.10.20"
        app.vm.network :private_network, ip: "192.168.56.20"
    end

end
